config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('movies.urls', 'movies'), namespace='movies')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

movies/urls.py
from django.urls import path

from movies.views import ViewMovies, ViewMovie, AddLikeToMovie, AddDislikeToMovie


urlpatterns = [
    path('', ViewMovies.as_view(), name='view-movies'),
    path('view-movie/<slug:movie_slug>', ViewMovie.as_view(), name='view-movie'),
    path('like-movie/<int:movie_pk>', AddLikeToMovie.as_view(), name='like-movie'),
    path('dislike-movie/<int:movie_pk>', AddDislikeToMovie.as_view(), name='dislike-movie'),
]

movies/models.py
import os
import re
from PIL import Image
from datetime import date, datetime

from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField('Category name', max_length=150, unique=True)
    description = models.TextField('Category description')
    url = models.SlugField('Slug for category', blank=True, max_length=300)

    def save(self,*args, **kwargs):
        if not self.url:
            url = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Genre(models.Model):
    name = models.CharField('Genre name', max_length=150, unique=True)
    description = models.TextField('Genre description')
    url = models.SlugField('Slug for genre', blank=True, max_length=300)

    def save(self,*args, **kwargs):
        if not self.url:
            url = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name




class Actor(models.Model):
    def actor_image_path_heandler(instance, filename):
        """Uploading actor image, if user set new one, deleting the old"""
        actor_img_name = f'actors/actor_{instance.pk}/actor_img.jpg'
        full_img_path = os.path.join(settings.MEDIA_ROOT, actor_img_name)

        # Deleting old image if exists
        if os.path.exists(full_img_path):
            os.remove(full_img_path)
        return actor_img_name

    first_name = models.CharField(max_length=100)
    second_name = models.CharField(max_length=100)
    date_of_birth = models.DateField('Actor date of the birth')
    biography = models.CharField('Actor biography', max_length=5000, blank=True, null=True)
    actor_image = models.ImageField('Actor photo', blank=True, upload_to=actor_image_path_heandler, default='user/default-img.jpg')

    def clean(self):
        if self.date_of_birth > date.today():
            raise ValidationError("Wrong date of birth!")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.actor_image:
            SIZE = 300, 300
            picture = Image.open(self.actor_image.path)
            picture.thumbnail(SIZE, Image.LANCZOS)
            picture.save(self.actor_image.path)

    def get_age(self):
        return datetime.today().year - self.date_of_birth.year

    def __str__(self):
        return f'{self.first_name} {self.second_name},'


class Country(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def clean(self):
        if re.match(r'[0-9]+', self.name):
            raise ValidationError("Name of the country can't contain numbers!")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'



class Movie(models.Model):

    def movie_title_image_path_headler(instance, filename):
        """Uploading movie title image, if user set new one, deleting the old"""
        movie_title_img_name = f'movies/movie_{instance.pk}/movie_title_img.jpg'
        full_img_path = os.path.join(settings.MEDIA_ROOT, movie_title_img_name)

        # Deleting old image if exists
        if os.path.exists(full_img_path):
            os.remove(full_img_path)
        return movie_title_img_name

    AGE_CHOICES = (
        ('0+', '0+'),
        ('6+', '6+'),
        ('12+', '12+'),
        ('16+', '16+'),
        ('18+', '18+'),
    )

    name = models.CharField('Movie name', max_length=150, unique=True)
    category = models.ManyToManyField(Category, verbose_name='Category')
    genres = models.ManyToManyField(Genre, verbose_name='Movie genres')
    title_image = models.ImageField('Title image for movie', upload_to=movie_title_image_path_headler)
    world_rating = models.PositiveSmallIntegerField('Movie world rating', default=0)
    country = models.ManyToManyField(Country, verbose_name='Movie country')
    world_fees = models.PositiveIntegerField('Fees in world')
    budget = models.PositiveIntegerField('Movie budget')
    world_premier = models.DateField('Movie world premier')
    is_published = models.BooleanField('is published', default=False)
    discription = models.TextField('Movie description')
    actors = models.ManyToManyField(Actor, verbose_name='Actors', related_name='movie_actors')
    directors = models.ManyToManyField(Actor, verbose_name='Directors', related_name='movie_directors')
    url = models.SlugField('Slug for movie', max_length=300, blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='movie_likes')
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='movie_dislikes')
    min_viewing_age = models.CharField(max_length=6, choices=AGE_CHOICES)

    def save(self, *args, **kwargs):
        if not self.url:
            url = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absloute_url(self):
        return reverse_lazy('movies:view-movie', kwargs={'movie_slug': self.url})

    def clean(self):
        if self.world_rating > 10 or self.world_rating < 0:
            raise ValidationError("Invalid world rating")

    def __str__(self):
        return self.name

    @property
    def get_total_likes(self):
        return self.likes.count()


class Review(models.Model):
    movie = models.ForeignKey(Movie, related_name='reviews_to_movie', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField('Comment', max_length=5000)
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='review_likes')
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='review_dislikes')
    parent = models.ForeignKey('self', verbose_name='parent', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.movie.name} - {self.user}'

movies/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

from .models import Movie

from .services import add_like_to_the_movie, add_dislike_to_the_movie


class ViewMovies(ListView):
    model = Movie
    template_name = 'movies/view_movies.html'
    context_object_name = 'movies'
    ordering = ['-world_rating']


class ViewMovie(DetailView):
    model = Movie
    template_name = 'movies/view_movie.html'
    context_object_name = 'movie'
    slug_field = 'url'
    slug_url_kwarg = 'movie_slug'


class AddLikeToMovie(LoginRequiredMixin, View):
    def post(self, request, movie_pk, *args, **kwargs):
        movie = get_object_or_404(Movie, pk=movie_pk)
        add_like_to_the_movie(request, movie)
        return HttpResponseRedirect(reverse_lazy('movies:view-movie', args=[str(movie.url)]))


class AddDislikeToMovie(LoginRequiredMixin, View):
    def post(self, request, movie_pk, *args, **kwags):
        movie = get_object_or_404(Movie, pk=movie_pk)
        add_dislike_to_the_movie(request, movie)
        return HttpResponseRedirect(reverse_lazy('movies:view-movie', args=[str(movie.url)]))

movies/templates/movies/view_movie.html
{% extends 'base.html' %}

{% block title %} 
    View {{ movie.name }}
{% endblock %}


{% block content %}
    
    <style>
        .info_about_movie {
            float: right;
            padding: 50px;
        }
    </style>

    <div class="row">
        <div class="col-10 offset-1 col-sm-10 offset-sm-1 col-md-12 offset-md-0 my-5">
            <h2 class="text-center"> {{ movie.name }} </h2>
            <div class="info_about_movie">
                <img class="rounded" src="{{movie.title_image.url}}" width="300" height="400">
                <br> 
                <strong> 
                    Genre:
                    {% for genre in movie.genres.all  %}
                        {{ genre }}, 
                    {% endfor %}
                    <br>
                    Movie actors:
                    {% for actor in movie.actors.all  %}
                        {{ actor }}, 
                    {% endfor %}
                    <br>
                    Movie directors:
                    {% for director in movie.directors.all  %}
                        {{ director }}, 
                    {% endfor %}
                    <br>
                    Movie budget: {{ movie.budget }}$,
                    <br>
                    World fees: {{ movie.world_fees }}$,
                    <br>
                    World premier: {{ movie.world_premier }}
                    <br>
                    World rating: {{ movie.world_rating }}/10
                </strong>
            </div>
            <br><br>
            {{ movie.discription|safe|linebreaks  }}
            <form method="POST" action="{% url 'movies:like-movie' movie.pk %}">
                {% csrf_token %}
                <input type="hidden" name"next" value="{{ request.path }}"> 
                <button type="submit" class="btn btn-success">
                    Like movie - {{ movie.likes.all.count }}
                </button>
            </form>

            </br>

            <form method="POST" action="{% url 'movies:dislike-movie' movie.pk %}">
                {% csrf_token %}
                <input type="hidden" name"next" value="{{ request.path }}"> 
                <button type="submit" class="btn btn-danger">
                    Dislike movie - {{ movie.dislikes.all.count }}
                </button>
            </form>
        </div>
    </div>
{% endblock %}

movies/templates/movies/view_movies.html
{% extends 'base.html' %}



{% block title %} 
    View movies 
{% endblock %}



{% block content %}
    <div class="row">
        {% for movie in movies %}
            <div class="col-sm-10 offset-sm-2 col-md-6 offset-md-0 col-lg-5 col-xl-4 my-2">
                <br>
                <div class="card h-100" style="width: 16rem;">
                    <img src="{{ movie.title_image.url }}" class="card-img-top" class="rounded" alt="..." height="350px" >
                    <div class="card-body">
                      <h5 class="card-title"> {{ movie.name  }}</h5>
                        <p class="card-text"> {{ movie.discription|truncatechars:30 }} </p>
                        <p style="padding: 5px;"> World rating: {{ movie.world_rating }}/10, <br> Age recommendations: {{movie.min_viewing_age}} </p>
                        <a href="{{ movie.get_absloute_url }}" class="btn btn-success">View more</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
</div>