accounts/urls.py
from django.urls import path

from accounts.views import UserRegistration, UserAuthentication, logout_view, EditProfile, ViewProfile


urlpatterns = [
    path('registration/', UserRegistration.as_view(), name='registration'),
    path('login/', UserAuthentication.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),

    path('edit-pofile/<slug:username_slug>', EditProfile.as_view(), name='edit-profile'),
    path('view-pofile/<slug:username_slug>', ViewProfile.as_view(), name='view-profile'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('movies.urls', 'movies'), namespace='movies')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

movies/urls.py
from django.urls import path

from movies.views import ViewMovies, ViewMovie, AddLikeToMovie, AddDislikeToMovie


urlpatterns = [
    path('', ViewMovies.as_view(), name='view-movies'),
    path('view-movie/<slug:movie_slug>', ViewMovie.as_view(), name='view-movie'),
    path('like-movie/<int:movie_pk>', AddLikeToMovie.as_view(), name='like-movie'),
    path('dislike-movie/<int:movie_pk>', AddDislikeToMovie.as_view(), name='dislike-movie'),
]

templates/inc/_form.html
<div class="row">
    <div class="col-md-5 mx-auto">
        {{ header }}
        <form action="{{ action }}" method="post">

            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit" class="{{ btn_class }}">
                {{ btn_message }}
            </button>
        </form>
    </div>
</div>

templates/inc/_nav.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark main-nav">
    <div class="container">
        <div class="navbar-brand" > 
            <a href="{% url 'movies:view-movies' %}"><img src="{% static 'logo/grovie-logo-1.png' %}" class="img-responsive" width="200px" height="60px"></a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span> 
        </button>

        <div id="main-menu" class="collapse navbar-collapse">
            <ul class="nav navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movies:view-movies' %}"> Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"> About </a>
                </li>
            </ul>
        </div>

        <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle mx-4" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     Profile 
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'accounts:view-profile' username_slug=user.username %}"> View Profile </a></li>
                    <li><a class="dropdown-item" href="#"> Watch list </a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:edit-profile' username_slug=user.username  %}"> Edit Profile </a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"> Logout </a></li>
                  </ul>
                </li>
            {% else %}
                <span class="navbar-text">
                    <a href="{% url 'accounts:registration' %}"> registration </a> | 
                    <a href="{% url 'accounts:login' %}"> login </a>
                </span>
            {% endif %}
        </ul>
    </div>
</nav>